/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 8.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace pb.locationIntelligence.Model
{
    /// <summary>
    /// CarrierRouteResponse
    /// </summary>
    [DataContract]
    public partial class CarrierRouteResponse :  IEquatable<CarrierRouteResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CarrierRouteResponse" /> class.
        /// </summary>
        /// <param name="ObjectId">ObjectId.</param>
        /// <param name="MatchedAddress">MatchedAddress.</param>
        /// <param name="Code">Code.</param>
        /// <param name="State">State.</param>
        /// <param name="CountyFips">CountyFips.</param>
        /// <param name="PostalTown">PostalTown.</param>
        /// <param name="PostCode">PostCode.</param>
        /// <param name="RouteDelivery">RouteDelivery.</param>
        /// <param name="Boundary">Boundary.</param>
        /// <param name="BoundaryRef">BoundaryRef.</param>
        public CarrierRouteResponse(string ObjectId = null, MatchedAddress MatchedAddress = null, string Code = null, CommonState State = null, string CountyFips = null, string PostalTown = null, string PostCode = null, RouteDelivery RouteDelivery = null, RouteBoundary Boundary = null, string BoundaryRef = null)
        {
            this.ObjectId = ObjectId;
            this.MatchedAddress = MatchedAddress;
            this.Code = Code;
            this.State = State;
            this.CountyFips = CountyFips;
            this.PostalTown = PostalTown;
            this.PostCode = PostCode;
            this.RouteDelivery = RouteDelivery;
            this.Boundary = Boundary;
            this.BoundaryRef = BoundaryRef;
        }
        
        /// <summary>
        /// Gets or Sets ObjectId
        /// </summary>
        [DataMember(Name="objectId", EmitDefaultValue=false)]
        public string ObjectId { get; set; }
        /// <summary>
        /// Gets or Sets MatchedAddress
        /// </summary>
        [DataMember(Name="matchedAddress", EmitDefaultValue=false)]
        public MatchedAddress MatchedAddress { get; set; }
        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }
        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public CommonState State { get; set; }
        /// <summary>
        /// Gets or Sets CountyFips
        /// </summary>
        [DataMember(Name="countyFips", EmitDefaultValue=false)]
        public string CountyFips { get; set; }
        /// <summary>
        /// Gets or Sets PostalTown
        /// </summary>
        [DataMember(Name="postalTown", EmitDefaultValue=false)]
        public string PostalTown { get; set; }
        /// <summary>
        /// Gets or Sets PostCode
        /// </summary>
        [DataMember(Name="postCode", EmitDefaultValue=false)]
        public string PostCode { get; set; }
        /// <summary>
        /// Gets or Sets RouteDelivery
        /// </summary>
        [DataMember(Name="routeDelivery", EmitDefaultValue=false)]
        public RouteDelivery RouteDelivery { get; set; }
        /// <summary>
        /// Gets or Sets Boundary
        /// </summary>
        [DataMember(Name="boundary", EmitDefaultValue=false)]
        public RouteBoundary Boundary { get; set; }
        /// <summary>
        /// Gets or Sets BoundaryRef
        /// </summary>
        [DataMember(Name="boundaryRef", EmitDefaultValue=false)]
        public string BoundaryRef { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CarrierRouteResponse {\n");
            sb.Append("  ObjectId: ").Append(ObjectId).Append("\n");
            sb.Append("  MatchedAddress: ").Append(MatchedAddress).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  CountyFips: ").Append(CountyFips).Append("\n");
            sb.Append("  PostalTown: ").Append(PostalTown).Append("\n");
            sb.Append("  PostCode: ").Append(PostCode).Append("\n");
            sb.Append("  RouteDelivery: ").Append(RouteDelivery).Append("\n");
            sb.Append("  Boundary: ").Append(Boundary).Append("\n");
            sb.Append("  BoundaryRef: ").Append(BoundaryRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CarrierRouteResponse);
        }

        /// <summary>
        /// Returns true if CarrierRouteResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CarrierRouteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CarrierRouteResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ObjectId == other.ObjectId ||
                    this.ObjectId != null &&
                    this.ObjectId.Equals(other.ObjectId)
                ) && 
                (
                    this.MatchedAddress == other.MatchedAddress ||
                    this.MatchedAddress != null &&
                    this.MatchedAddress.Equals(other.MatchedAddress)
                ) && 
                (
                    this.Code == other.Code ||
                    this.Code != null &&
                    this.Code.Equals(other.Code)
                ) && 
                (
                    this.State == other.State ||
                    this.State != null &&
                    this.State.Equals(other.State)
                ) && 
                (
                    this.CountyFips == other.CountyFips ||
                    this.CountyFips != null &&
                    this.CountyFips.Equals(other.CountyFips)
                ) && 
                (
                    this.PostalTown == other.PostalTown ||
                    this.PostalTown != null &&
                    this.PostalTown.Equals(other.PostalTown)
                ) && 
                (
                    this.PostCode == other.PostCode ||
                    this.PostCode != null &&
                    this.PostCode.Equals(other.PostCode)
                ) && 
                (
                    this.RouteDelivery == other.RouteDelivery ||
                    this.RouteDelivery != null &&
                    this.RouteDelivery.Equals(other.RouteDelivery)
                ) && 
                (
                    this.Boundary == other.Boundary ||
                    this.Boundary != null &&
                    this.Boundary.Equals(other.Boundary)
                ) && 
                (
                    this.BoundaryRef == other.BoundaryRef ||
                    this.BoundaryRef != null &&
                    this.BoundaryRef.Equals(other.BoundaryRef)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ObjectId != null)
                    hash = hash * 59 + this.ObjectId.GetHashCode();
                if (this.MatchedAddress != null)
                    hash = hash * 59 + this.MatchedAddress.GetHashCode();
                if (this.Code != null)
                    hash = hash * 59 + this.Code.GetHashCode();
                if (this.State != null)
                    hash = hash * 59 + this.State.GetHashCode();
                if (this.CountyFips != null)
                    hash = hash * 59 + this.CountyFips.GetHashCode();
                if (this.PostalTown != null)
                    hash = hash * 59 + this.PostalTown.GetHashCode();
                if (this.PostCode != null)
                    hash = hash * 59 + this.PostCode.GetHashCode();
                if (this.RouteDelivery != null)
                    hash = hash * 59 + this.RouteDelivery.GetHashCode();
                if (this.Boundary != null)
                    hash = hash * 59 + this.Boundary.GetHashCode();
                if (this.BoundaryRef != null)
                    hash = hash * 59 + this.BoundaryRef.GetHashCode();
                return hash;
            }
        }
    }

}
