/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace pb.locationIntelligence.Model
{
    /// <summary>
    /// DemographicsThemesV2
    /// </summary>
    [DataContract]
    public partial class DemographicsThemesV2 :  IEquatable<DemographicsThemesV2>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DemographicsThemesV2" /> class.
        /// </summary>
        /// <param name="PopulationTheme">PopulationTheme.</param>
        /// <param name="RaceAndEthnicityTheme">RaceAndEthnicityTheme.</param>
        /// <param name="HealthTheme">HealthTheme.</param>
        /// <param name="EducationTheme">EducationTheme.</param>
        /// <param name="IncomeTheme">IncomeTheme.</param>
        /// <param name="AssetsAndWealthTheme">AssetsAndWealthTheme.</param>
        /// <param name="HouseholdsTheme">HouseholdsTheme.</param>
        /// <param name="HousingTheme">HousingTheme.</param>
        /// <param name="EmploymentTheme">EmploymentTheme.</param>
        /// <param name="ExpenditureTheme">ExpenditureTheme.</param>
        /// <param name="SupplyAndDemandTheme">SupplyAndDemandTheme.</param>
        public DemographicsThemesV2(PopulationTheme PopulationTheme = null, RaceAndEthnicityTheme RaceAndEthnicityTheme = null, HealthTheme HealthTheme = null, EducationTheme EducationTheme = null, IncomeThemeV2 IncomeTheme = null, AssetsAndWealthTheme AssetsAndWealthTheme = null, HouseholdsTheme HouseholdsTheme = null, HousingTheme HousingTheme = null, EmploymentTheme EmploymentTheme = null, ExpenditureTheme ExpenditureTheme = null, SupplyAndDemandTheme SupplyAndDemandTheme = null)
        {
            this.PopulationTheme = PopulationTheme;
            this.RaceAndEthnicityTheme = RaceAndEthnicityTheme;
            this.HealthTheme = HealthTheme;
            this.EducationTheme = EducationTheme;
            this.IncomeTheme = IncomeTheme;
            this.AssetsAndWealthTheme = AssetsAndWealthTheme;
            this.HouseholdsTheme = HouseholdsTheme;
            this.HousingTheme = HousingTheme;
            this.EmploymentTheme = EmploymentTheme;
            this.ExpenditureTheme = ExpenditureTheme;
            this.SupplyAndDemandTheme = SupplyAndDemandTheme;
        }
        
        /// <summary>
        /// Gets or Sets PopulationTheme
        /// </summary>
        [DataMember(Name="populationTheme", EmitDefaultValue=false)]
        public PopulationTheme PopulationTheme { get; set; }
        /// <summary>
        /// Gets or Sets RaceAndEthnicityTheme
        /// </summary>
        [DataMember(Name="raceAndEthnicityTheme", EmitDefaultValue=false)]
        public RaceAndEthnicityTheme RaceAndEthnicityTheme { get; set; }
        /// <summary>
        /// Gets or Sets HealthTheme
        /// </summary>
        [DataMember(Name="healthTheme", EmitDefaultValue=false)]
        public HealthTheme HealthTheme { get; set; }
        /// <summary>
        /// Gets or Sets EducationTheme
        /// </summary>
        [DataMember(Name="educationTheme", EmitDefaultValue=false)]
        public EducationTheme EducationTheme { get; set; }
        /// <summary>
        /// Gets or Sets IncomeTheme
        /// </summary>
        [DataMember(Name="incomeTheme", EmitDefaultValue=false)]
        public IncomeThemeV2 IncomeTheme { get; set; }
        /// <summary>
        /// Gets or Sets AssetsAndWealthTheme
        /// </summary>
        [DataMember(Name="assetsAndWealthTheme", EmitDefaultValue=false)]
        public AssetsAndWealthTheme AssetsAndWealthTheme { get; set; }
        /// <summary>
        /// Gets or Sets HouseholdsTheme
        /// </summary>
        [DataMember(Name="householdsTheme", EmitDefaultValue=false)]
        public HouseholdsTheme HouseholdsTheme { get; set; }
        /// <summary>
        /// Gets or Sets HousingTheme
        /// </summary>
        [DataMember(Name="housingTheme", EmitDefaultValue=false)]
        public HousingTheme HousingTheme { get; set; }
        /// <summary>
        /// Gets or Sets EmploymentTheme
        /// </summary>
        [DataMember(Name="employmentTheme", EmitDefaultValue=false)]
        public EmploymentTheme EmploymentTheme { get; set; }
        /// <summary>
        /// Gets or Sets ExpenditureTheme
        /// </summary>
        [DataMember(Name="expenditureTheme", EmitDefaultValue=false)]
        public ExpenditureTheme ExpenditureTheme { get; set; }
        /// <summary>
        /// Gets or Sets SupplyAndDemandTheme
        /// </summary>
        [DataMember(Name="supplyAndDemandTheme", EmitDefaultValue=false)]
        public SupplyAndDemandTheme SupplyAndDemandTheme { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DemographicsThemesV2 {\n");
            sb.Append("  PopulationTheme: ").Append(PopulationTheme).Append("\n");
            sb.Append("  RaceAndEthnicityTheme: ").Append(RaceAndEthnicityTheme).Append("\n");
            sb.Append("  HealthTheme: ").Append(HealthTheme).Append("\n");
            sb.Append("  EducationTheme: ").Append(EducationTheme).Append("\n");
            sb.Append("  IncomeTheme: ").Append(IncomeTheme).Append("\n");
            sb.Append("  AssetsAndWealthTheme: ").Append(AssetsAndWealthTheme).Append("\n");
            sb.Append("  HouseholdsTheme: ").Append(HouseholdsTheme).Append("\n");
            sb.Append("  HousingTheme: ").Append(HousingTheme).Append("\n");
            sb.Append("  EmploymentTheme: ").Append(EmploymentTheme).Append("\n");
            sb.Append("  ExpenditureTheme: ").Append(ExpenditureTheme).Append("\n");
            sb.Append("  SupplyAndDemandTheme: ").Append(SupplyAndDemandTheme).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DemographicsThemesV2);
        }

        /// <summary>
        /// Returns true if DemographicsThemesV2 instances are equal
        /// </summary>
        /// <param name="other">Instance of DemographicsThemesV2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DemographicsThemesV2 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PopulationTheme == other.PopulationTheme ||
                    this.PopulationTheme != null &&
                    this.PopulationTheme.Equals(other.PopulationTheme)
                ) && 
                (
                    this.RaceAndEthnicityTheme == other.RaceAndEthnicityTheme ||
                    this.RaceAndEthnicityTheme != null &&
                    this.RaceAndEthnicityTheme.Equals(other.RaceAndEthnicityTheme)
                ) && 
                (
                    this.HealthTheme == other.HealthTheme ||
                    this.HealthTheme != null &&
                    this.HealthTheme.Equals(other.HealthTheme)
                ) && 
                (
                    this.EducationTheme == other.EducationTheme ||
                    this.EducationTheme != null &&
                    this.EducationTheme.Equals(other.EducationTheme)
                ) && 
                (
                    this.IncomeTheme == other.IncomeTheme ||
                    this.IncomeTheme != null &&
                    this.IncomeTheme.Equals(other.IncomeTheme)
                ) && 
                (
                    this.AssetsAndWealthTheme == other.AssetsAndWealthTheme ||
                    this.AssetsAndWealthTheme != null &&
                    this.AssetsAndWealthTheme.Equals(other.AssetsAndWealthTheme)
                ) && 
                (
                    this.HouseholdsTheme == other.HouseholdsTheme ||
                    this.HouseholdsTheme != null &&
                    this.HouseholdsTheme.Equals(other.HouseholdsTheme)
                ) && 
                (
                    this.HousingTheme == other.HousingTheme ||
                    this.HousingTheme != null &&
                    this.HousingTheme.Equals(other.HousingTheme)
                ) && 
                (
                    this.EmploymentTheme == other.EmploymentTheme ||
                    this.EmploymentTheme != null &&
                    this.EmploymentTheme.Equals(other.EmploymentTheme)
                ) && 
                (
                    this.ExpenditureTheme == other.ExpenditureTheme ||
                    this.ExpenditureTheme != null &&
                    this.ExpenditureTheme.Equals(other.ExpenditureTheme)
                ) && 
                (
                    this.SupplyAndDemandTheme == other.SupplyAndDemandTheme ||
                    this.SupplyAndDemandTheme != null &&
                    this.SupplyAndDemandTheme.Equals(other.SupplyAndDemandTheme)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PopulationTheme != null)
                    hash = hash * 59 + this.PopulationTheme.GetHashCode();
                if (this.RaceAndEthnicityTheme != null)
                    hash = hash * 59 + this.RaceAndEthnicityTheme.GetHashCode();
                if (this.HealthTheme != null)
                    hash = hash * 59 + this.HealthTheme.GetHashCode();
                if (this.EducationTheme != null)
                    hash = hash * 59 + this.EducationTheme.GetHashCode();
                if (this.IncomeTheme != null)
                    hash = hash * 59 + this.IncomeTheme.GetHashCode();
                if (this.AssetsAndWealthTheme != null)
                    hash = hash * 59 + this.AssetsAndWealthTheme.GetHashCode();
                if (this.HouseholdsTheme != null)
                    hash = hash * 59 + this.HouseholdsTheme.GetHashCode();
                if (this.HousingTheme != null)
                    hash = hash * 59 + this.HousingTheme.GetHashCode();
                if (this.EmploymentTheme != null)
                    hash = hash * 59 + this.EmploymentTheme.GetHashCode();
                if (this.ExpenditureTheme != null)
                    hash = hash * 59 + this.ExpenditureTheme.GetHashCode();
                if (this.SupplyAndDemandTheme != null)
                    hash = hash * 59 + this.SupplyAndDemandTheme.GetHashCode();
                return hash;
            }
        }
    }

}
