/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 8.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace pb.locationIntelligence.Model
{
    /// <summary>
    /// TaxAddressRequest
    /// </summary>
    [DataContract]
    public partial class TaxAddressRequest :  IEquatable<TaxAddressRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxAddressRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TaxAddressRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxAddressRequest" /> class.
        /// </summary>
        /// <param name="Preferences">Preferences.</param>
        /// <param name="TaxAddresses">TaxAddresses (required).</param>
        public TaxAddressRequest(Preferences Preferences = null, List<TaxAddress> TaxAddresses = null)
        {
            // to ensure "TaxAddresses" is required (not null)
            if (TaxAddresses == null)
            {
                throw new InvalidDataException("TaxAddresses is a required property for TaxAddressRequest and cannot be null");
            }
            else
            {
                this.TaxAddresses = TaxAddresses;
            }
            this.Preferences = Preferences;
        }
        
        /// <summary>
        /// Gets or Sets Preferences
        /// </summary>
        [DataMember(Name="preferences", EmitDefaultValue=false)]
        public Preferences Preferences { get; set; }
        /// <summary>
        /// Gets or Sets TaxAddresses
        /// </summary>
        [DataMember(Name="taxAddresses", EmitDefaultValue=false)]
        public List<TaxAddress> TaxAddresses { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaxAddressRequest {\n");
            sb.Append("  Preferences: ").Append(Preferences).Append("\n");
            sb.Append("  TaxAddresses: ").Append(TaxAddresses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TaxAddressRequest);
        }

        /// <summary>
        /// Returns true if TaxAddressRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TaxAddressRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaxAddressRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Preferences == other.Preferences ||
                    this.Preferences != null &&
                    this.Preferences.Equals(other.Preferences)
                ) && 
                (
                    this.TaxAddresses == other.TaxAddresses ||
                    this.TaxAddresses != null &&
                    this.TaxAddresses.SequenceEqual(other.TaxAddresses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Preferences != null)
                    hash = hash * 59 + this.Preferences.GetHashCode();
                if (this.TaxAddresses != null)
                    hash = hash * 59 + this.TaxAddresses.GetHashCode();
                return hash;
            }
        }
    }

}
