/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 4.6.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing CarrierRouteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarrierRouteResponseTests
    {
        // TODO uncomment below to declare an instance variable for CarrierRouteResponse
        //private CarrierRouteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierRouteResponse
            //instance = new CarrierRouteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierRouteResponse
        /// </summary>
        [Test]
        public void CarrierRouteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CarrierRouteResponse
            //Assert.IsInstanceOfType<CarrierRouteResponse> (instance, "variable 'instance' is a CarrierRouteResponse");
        }

        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'MatchedAddress'
        /// </summary>
        [Test]
        public void MatchedAddressTest()
        {
            // TODO unit test for the property 'MatchedAddress'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'CountyFips'
        /// </summary>
        [Test]
        public void CountyFipsTest()
        {
            // TODO unit test for the property 'CountyFips'
        }
        /// <summary>
        /// Test the property 'PostalTown'
        /// </summary>
        [Test]
        public void PostalTownTest()
        {
            // TODO unit test for the property 'PostalTown'
        }
        /// <summary>
        /// Test the property 'PostCode'
        /// </summary>
        [Test]
        public void PostCodeTest()
        {
            // TODO unit test for the property 'PostCode'
        }
        /// <summary>
        /// Test the property 'RouteDelivery'
        /// </summary>
        [Test]
        public void RouteDeliveryTest()
        {
            // TODO unit test for the property 'RouteDelivery'
        }
        /// <summary>
        /// Test the property 'Boundary'
        /// </summary>
        [Test]
        public void BoundaryTest()
        {
            // TODO unit test for the property 'Boundary'
        }
        /// <summary>
        /// Test the property 'BoundaryRef'
        /// </summary>
        [Test]
        public void BoundaryRefTest()
        {
            // TODO unit test for the property 'BoundaryRef'
        }

    }

}
