/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 6.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing EarthquakeEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EarthquakeEventTests
    {
        // TODO uncomment below to declare an instance variable for EarthquakeEvent
        //private EarthquakeEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EarthquakeEvent
            //instance = new EarthquakeEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EarthquakeEvent
        /// </summary>
        [Test]
        public void EarthquakeEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EarthquakeEvent
            //Assert.IsInstanceOfType<EarthquakeEvent> (instance, "variable 'instance' is a EarthquakeEvent");
        }

        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'SeismicRegionNumber'
        /// </summary>
        [Test]
        public void SeismicRegionNumberTest()
        {
            // TODO unit test for the property 'SeismicRegionNumber'
        }
        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Test]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }
        /// <summary>
        /// Test the property 'Magnitude'
        /// </summary>
        [Test]
        public void MagnitudeTest()
        {
            // TODO unit test for the property 'Magnitude'
        }
        /// <summary>
        /// Test the property 'Cause'
        /// </summary>
        [Test]
        public void CauseTest()
        {
            // TODO unit test for the property 'Cause'
        }
        /// <summary>
        /// Test the property 'CulturalEffect'
        /// </summary>
        [Test]
        public void CulturalEffectTest()
        {
            // TODO unit test for the property 'CulturalEffect'
        }
        /// <summary>
        /// Test the property 'Intensity'
        /// </summary>
        [Test]
        public void IntensityTest()
        {
            // TODO unit test for the property 'Intensity'
        }
        /// <summary>
        /// Test the property 'Diastrophism'
        /// </summary>
        [Test]
        public void DiastrophismTest()
        {
            // TODO unit test for the property 'Diastrophism'
        }
        /// <summary>
        /// Test the property 'MiscPhenomena'
        /// </summary>
        [Test]
        public void MiscPhenomenaTest()
        {
            // TODO unit test for the property 'MiscPhenomena'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

    }

}
