/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 4.6.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing EventsCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventsCountTests
    {
        // TODO uncomment below to declare an instance variable for EventsCount
        //private EventsCount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventsCount
            //instance = new EventsCount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventsCount
        /// </summary>
        [Test]
        public void EventsCountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventsCount
            //Assert.IsInstanceOfType<EventsCount> (instance, "variable 'instance' is a EventsCount");
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'R0'
        /// </summary>
        [Test]
        public void R0Test()
        {
            // TODO unit test for the property 'R0'
        }
        /// <summary>
        /// Test the property 'R1'
        /// </summary>
        [Test]
        public void R1Test()
        {
            // TODO unit test for the property 'R1'
        }
        /// <summary>
        /// Test the property 'R2'
        /// </summary>
        [Test]
        public void R2Test()
        {
            // TODO unit test for the property 'R2'
        }
        /// <summary>
        /// Test the property 'R3'
        /// </summary>
        [Test]
        public void R3Test()
        {
            // TODO unit test for the property 'R3'
        }
        /// <summary>
        /// Test the property 'R4'
        /// </summary>
        [Test]
        public void R4Test()
        {
            // TODO unit test for the property 'R4'
        }
        /// <summary>
        /// Test the property 'R5'
        /// </summary>
        [Test]
        public void R5Test()
        {
            // TODO unit test for the property 'R5'
        }
        /// <summary>
        /// Test the property 'R6'
        /// </summary>
        [Test]
        public void R6Test()
        {
            // TODO unit test for the property 'R6'
        }
        /// <summary>
        /// Test the property 'R7'
        /// </summary>
        [Test]
        public void R7Test()
        {
            // TODO unit test for the property 'R7'
        }
        /// <summary>
        /// Test the property 'R0Ge'
        /// </summary>
        [Test]
        public void R0GeTest()
        {
            // TODO unit test for the property 'R0Ge'
        }
        /// <summary>
        /// Test the property 'R1Ge'
        /// </summary>
        [Test]
        public void R1GeTest()
        {
            // TODO unit test for the property 'R1Ge'
        }
        /// <summary>
        /// Test the property 'R2Ge'
        /// </summary>
        [Test]
        public void R2GeTest()
        {
            // TODO unit test for the property 'R2Ge'
        }
        /// <summary>
        /// Test the property 'R3Ge'
        /// </summary>
        [Test]
        public void R3GeTest()
        {
            // TODO unit test for the property 'R3Ge'
        }
        /// <summary>
        /// Test the property 'R4Ge'
        /// </summary>
        [Test]
        public void R4GeTest()
        {
            // TODO unit test for the property 'R4Ge'
        }
        /// <summary>
        /// Test the property 'R5Ge'
        /// </summary>
        [Test]
        public void R5GeTest()
        {
            // TODO unit test for the property 'R5Ge'
        }
        /// <summary>
        /// Test the property 'R6Ge'
        /// </summary>
        [Test]
        public void R6GeTest()
        {
            // TODO unit test for the property 'R6Ge'
        }
        /// <summary>
        /// Test the property 'R7Ge'
        /// </summary>
        [Test]
        public void R7GeTest()
        {
            // TODO unit test for the property 'R7Ge'
        }

    }

}
