/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 6.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing GeocodeCustomPreferences
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeocodeCustomPreferencesTests
    {
        // TODO uncomment below to declare an instance variable for GeocodeCustomPreferences
        //private GeocodeCustomPreferences instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeocodeCustomPreferences
            //instance = new GeocodeCustomPreferences();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeocodeCustomPreferences
        /// </summary>
        [Test]
        public void GeocodeCustomPreferencesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeocodeCustomPreferences
            //Assert.IsInstanceOfType<GeocodeCustomPreferences> (instance, "variable 'instance' is a GeocodeCustomPreferences");
        }

        /// <summary>
        /// Test the property 'FALLBACK_TO_WORLD'
        /// </summary>
        [Test]
        public void FALLBACK_TO_WORLDTest()
        {
            // TODO unit test for the property 'FALLBACK_TO_WORLD'
        }
        /// <summary>
        /// Test the property 'USE_ADDRESS_POINT_INTERPOLATION'
        /// </summary>
        [Test]
        public void USE_ADDRESS_POINT_INTERPOLATIONTest()
        {
            // TODO unit test for the property 'USE_ADDRESS_POINT_INTERPOLATION'
        }
        /// <summary>
        /// Test the property 'USE_CENTERLINE_OFFSET'
        /// </summary>
        [Test]
        public void USE_CENTERLINE_OFFSETTest()
        {
            // TODO unit test for the property 'USE_CENTERLINE_OFFSET'
        }
        /// <summary>
        /// Test the property 'CENTERLINE_OFFSET'
        /// </summary>
        [Test]
        public void CENTERLINE_OFFSETTest()
        {
            // TODO unit test for the property 'CENTERLINE_OFFSET'
        }

    }

}
