/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 8.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing GradeLevelsTaught
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GradeLevelsTaughtTests
    {
        // TODO uncomment below to declare an instance variable for GradeLevelsTaught
        //private GradeLevelsTaught instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GradeLevelsTaught
            //instance = new GradeLevelsTaught();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GradeLevelsTaught
        /// </summary>
        [Test]
        public void GradeLevelsTaughtInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GradeLevelsTaught
            //Assert.IsInstanceOfType<GradeLevelsTaught> (instance, "variable 'instance' is a GradeLevelsTaught");
        }

        /// <summary>
        /// Test the property 'Pk'
        /// </summary>
        [Test]
        public void PkTest()
        {
            // TODO unit test for the property 'Pk'
        }
        /// <summary>
        /// Test the property 'Kg'
        /// </summary>
        [Test]
        public void KgTest()
        {
            // TODO unit test for the property 'Kg'
        }
        /// <summary>
        /// Test the property 'First'
        /// </summary>
        [Test]
        public void FirstTest()
        {
            // TODO unit test for the property 'First'
        }
        /// <summary>
        /// Test the property 'Second'
        /// </summary>
        [Test]
        public void SecondTest()
        {
            // TODO unit test for the property 'Second'
        }
        /// <summary>
        /// Test the property 'Third'
        /// </summary>
        [Test]
        public void ThirdTest()
        {
            // TODO unit test for the property 'Third'
        }
        /// <summary>
        /// Test the property 'Fourth'
        /// </summary>
        [Test]
        public void FourthTest()
        {
            // TODO unit test for the property 'Fourth'
        }
        /// <summary>
        /// Test the property 'Fifth'
        /// </summary>
        [Test]
        public void FifthTest()
        {
            // TODO unit test for the property 'Fifth'
        }
        /// <summary>
        /// Test the property 'Sixth'
        /// </summary>
        [Test]
        public void SixthTest()
        {
            // TODO unit test for the property 'Sixth'
        }
        /// <summary>
        /// Test the property 'Seventh'
        /// </summary>
        [Test]
        public void SeventhTest()
        {
            // TODO unit test for the property 'Seventh'
        }
        /// <summary>
        /// Test the property 'Eighth'
        /// </summary>
        [Test]
        public void EighthTest()
        {
            // TODO unit test for the property 'Eighth'
        }
        /// <summary>
        /// Test the property 'Ninth'
        /// </summary>
        [Test]
        public void NinthTest()
        {
            // TODO unit test for the property 'Ninth'
        }
        /// <summary>
        /// Test the property 'Tenth'
        /// </summary>
        [Test]
        public void TenthTest()
        {
            // TODO unit test for the property 'Tenth'
        }
        /// <summary>
        /// Test the property 'Eleventh'
        /// </summary>
        [Test]
        public void EleventhTest()
        {
            // TODO unit test for the property 'Eleventh'
        }
        /// <summary>
        /// Test the property 'Twelfth'
        /// </summary>
        [Test]
        public void TwelfthTest()
        {
            // TODO unit test for the property 'Twelfth'
        }

    }

}
