/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 7.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing Match
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatchTests
    {
        // TODO uncomment below to declare an instance variable for Match
        //private Match instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Match
            //instance = new Match();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Match
        /// </summary>
        [Test]
        public void MatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Match
            //Assert.IsInstanceOfType<Match> (instance, "variable 'instance' is a Match");
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Test]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
        /// <summary>
        /// Test the property 'PercentGeocode'
        /// </summary>
        [Test]
        public void PercentGeocodeTest()
        {
            // TODO unit test for the property 'PercentGeocode'
        }
        /// <summary>
        /// Test the property 'PrecisionLevel'
        /// </summary>
        [Test]
        public void PrecisionLevelTest()
        {
            // TODO unit test for the property 'PrecisionLevel'
        }
        /// <summary>
        /// Test the property 'LocationCode'
        /// </summary>
        [Test]
        public void LocationCodeTest()
        {
            // TODO unit test for the property 'LocationCode'
        }
        /// <summary>
        /// Test the property 'MatchCode'
        /// </summary>
        [Test]
        public void MatchCodeTest()
        {
            // TODO unit test for the property 'MatchCode'
        }

    }

}
