/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 7.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing Matrix
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatrixTests
    {
        // TODO uncomment below to declare an instance variable for Matrix
        //private Matrix instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Matrix
            //instance = new Matrix();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Matrix
        /// </summary>
        [Test]
        public void MatrixInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Matrix
            //Assert.IsInstanceOfType<Matrix> (instance, "variable 'instance' is a Matrix");
        }

        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'DistanceUnit'
        /// </summary>
        [Test]
        public void DistanceUnitTest()
        {
            // TODO unit test for the property 'DistanceUnit'
        }
        /// <summary>
        /// Test the property 'EndPoint'
        /// </summary>
        [Test]
        public void EndPointTest()
        {
            // TODO unit test for the property 'EndPoint'
        }
        /// <summary>
        /// Test the property 'StartPoint'
        /// </summary>
        [Test]
        public void StartPointTest()
        {
            // TODO unit test for the property 'StartPoint'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'TimeUnit'
        /// </summary>
        [Test]
        public void TimeUnitTest()
        {
            // TODO unit test for the property 'TimeUnit'
        }

    }

}
