/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 3.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing Network
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetworkTests
    {
        // TODO uncomment below to declare an instance variable for Network
        //private Network instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Network
            //instance = new Network();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Network
        /// </summary>
        [Test]
        public void NetworkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Network
            //Assert.IsInstanceOfType<Network> (instance, "variable 'instance' is a Network");
        }

        /// <summary>
        /// Test the property 'ConnectionFromHome'
        /// </summary>
        [Test]
        public void ConnectionFromHomeTest()
        {
            // TODO unit test for the property 'ConnectionFromHome'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Test]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'OrganizationType'
        /// </summary>
        [Test]
        public void OrganizationTypeTest()
        {
            // TODO unit test for the property 'OrganizationType'
        }
        /// <summary>
        /// Test the property 'ConnectionType'
        /// </summary>
        [Test]
        public void ConnectionTypeTest()
        {
            // TODO unit test for the property 'ConnectionType'
        }
        /// <summary>
        /// Test the property 'LineSpeed'
        /// </summary>
        [Test]
        public void LineSpeedTest()
        {
            // TODO unit test for the property 'LineSpeed'
        }
        /// <summary>
        /// Test the property 'IpRouteType'
        /// </summary>
        [Test]
        public void IpRouteTypeTest()
        {
            // TODO unit test for the property 'IpRouteType'
        }
        /// <summary>
        /// Test the property 'HostingFacility'
        /// </summary>
        [Test]
        public void HostingFacilityTest()
        {
            // TODO unit test for the property 'HostingFacility'
        }

    }

}
