/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 6.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing RateCenterResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RateCenterResponseTests
    {
        // TODO uncomment below to declare an instance variable for RateCenterResponse
        //private RateCenterResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RateCenterResponse
            //instance = new RateCenterResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RateCenterResponse
        /// </summary>
        [Test]
        public void RateCenterResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RateCenterResponse
            //Assert.IsInstanceOfType<RateCenterResponse> (instance, "variable 'instance' is a RateCenterResponse");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AlternateName'
        /// </summary>
        [Test]
        public void AlternateNameTest()
        {
            // TODO unit test for the property 'AlternateName'
        }
        /// <summary>
        /// Test the property 'AreaName1'
        /// </summary>
        [Test]
        public void AreaName1Test()
        {
            // TODO unit test for the property 'AreaName1'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'AreaCodeInfoList'
        /// </summary>
        [Test]
        public void AreaCodeInfoListTest()
        {
            // TODO unit test for the property 'AreaCodeInfoList'
        }
        /// <summary>
        /// Test the property 'MatchedAddress'
        /// </summary>
        [Test]
        public void MatchedAddressTest()
        {
            // TODO unit test for the property 'MatchedAddress'
        }
        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Test]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Test]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Test]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }

    }

}
