/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 8.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing SpeedLimit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpeedLimitTests
    {
        // TODO uncomment below to declare an instance variable for SpeedLimit
        //private SpeedLimit instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpeedLimit
            //instance = new SpeedLimit();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpeedLimit
        /// </summary>
        [Test]
        public void SpeedLimitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpeedLimit
            //Assert.IsInstanceOfType<SpeedLimit> (instance, "variable 'instance' is a SpeedLimit");
        }

        /// <summary>
        /// Test the property 'MaxSpeed'
        /// </summary>
        [Test]
        public void MaxSpeedTest()
        {
            // TODO unit test for the property 'MaxSpeed'
        }
        /// <summary>
        /// Test the property 'SpeedUnit'
        /// </summary>
        [Test]
        public void SpeedUnitTest()
        {
            // TODO unit test for the property 'SpeedUnit'
        }
        /// <summary>
        /// Test the property 'SpeedVerification'
        /// </summary>
        [Test]
        public void SpeedVerificationTest()
        {
            // TODO unit test for the property 'SpeedVerification'
        }
        /// <summary>
        /// Test the property 'AmPeakAvgSpeed'
        /// </summary>
        [Test]
        public void AmPeakAvgSpeedTest()
        {
            // TODO unit test for the property 'AmPeakAvgSpeed'
        }
        /// <summary>
        /// Test the property 'PmPeakAvgSpeed'
        /// </summary>
        [Test]
        public void PmPeakAvgSpeedTest()
        {
            // TODO unit test for the property 'PmPeakAvgSpeed'
        }
        /// <summary>
        /// Test the property 'OffPeakAvgSpeed'
        /// </summary>
        [Test]
        public void OffPeakAvgSpeedTest()
        {
            // TODO unit test for the property 'OffPeakAvgSpeed'
        }
        /// <summary>
        /// Test the property 'NightAvgSpeed'
        /// </summary>
        [Test]
        public void NightAvgSpeedTest()
        {
            // TODO unit test for the property 'NightAvgSpeed'
        }
        /// <summary>
        /// Test the property 'WeekAvgSpeed'
        /// </summary>
        [Test]
        public void WeekAvgSpeedTest()
        {
            // TODO unit test for the property 'WeekAvgSpeed'
        }
        /// <summary>
        /// Test the property 'Road'
        /// </summary>
        [Test]
        public void RoadTest()
        {
            // TODO unit test for the property 'Road'
        }

    }

}
