/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 8.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing TaxAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaxAddressTests
    {
        // TODO uncomment below to declare an instance variable for TaxAddress
        //private TaxAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaxAddress
            //instance = new TaxAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaxAddress
        /// </summary>
        [Test]
        public void TaxAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaxAddress
            //Assert.IsInstanceOfType<TaxAddress> (instance, "variable 'instance' is a TaxAddress");
        }

        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'MainAddressLine'
        /// </summary>
        [Test]
        public void MainAddressLineTest()
        {
            // TODO unit test for the property 'MainAddressLine'
        }
        /// <summary>
        /// Test the property 'PlaceName'
        /// </summary>
        [Test]
        public void PlaceNameTest()
        {
            // TODO unit test for the property 'PlaceName'
        }
        /// <summary>
        /// Test the property 'AreaName1'
        /// </summary>
        [Test]
        public void AreaName1Test()
        {
            // TODO unit test for the property 'AreaName1'
        }
        /// <summary>
        /// Test the property 'AreaName3'
        /// </summary>
        [Test]
        public void AreaName3Test()
        {
            // TODO unit test for the property 'AreaName3'
        }
        /// <summary>
        /// Test the property 'PostCode1'
        /// </summary>
        [Test]
        public void PostCode1Test()
        {
            // TODO unit test for the property 'PostCode1'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'PurchaseAmount'
        /// </summary>
        [Test]
        public void PurchaseAmountTest()
        {
            // TODO unit test for the property 'PurchaseAmount'
        }

    }

}
