/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 6.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing TaxBatchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaxBatchResponseTests
    {
        // TODO uncomment below to declare an instance variable for TaxBatchResponse
        //private TaxBatchResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaxBatchResponse
            //instance = new TaxBatchResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaxBatchResponse
        /// </summary>
        [Test]
        public void TaxBatchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaxBatchResponse
            //Assert.IsInstanceOfType<TaxBatchResponse> (instance, "variable 'instance' is a TaxBatchResponse");
        }

        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Test]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
        /// <summary>
        /// Test the property 'Jurisdiction'
        /// </summary>
        [Test]
        public void JurisdictionTest()
        {
            // TODO unit test for the property 'Jurisdiction'
        }
        /// <summary>
        /// Test the property 'MatchedAddress'
        /// </summary>
        [Test]
        public void MatchedAddressTest()
        {
            // TODO unit test for the property 'MatchedAddress'
        }
        /// <summary>
        /// Test the property 'SalesTax'
        /// </summary>
        [Test]
        public void SalesTaxTest()
        {
            // TODO unit test for the property 'SalesTax'
        }
        /// <summary>
        /// Test the property 'UseTax'
        /// </summary>
        [Test]
        public void UseTaxTest()
        {
            // TODO unit test for the property 'UseTax'
        }
        /// <summary>
        /// Test the property 'Census'
        /// </summary>
        [Test]
        public void CensusTest()
        {
            // TODO unit test for the property 'Census'
        }
        /// <summary>
        /// Test the property 'LatLongFields'
        /// </summary>
        [Test]
        public void LatLongFieldsTest()
        {
            // TODO unit test for the property 'LatLongFields'
        }

    }

}
