/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 8.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing TimezoneAddressRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimezoneAddressRequestTests
    {
        // TODO uncomment below to declare an instance variable for TimezoneAddressRequest
        //private TimezoneAddressRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimezoneAddressRequest
            //instance = new TimezoneAddressRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimezoneAddressRequest
        /// </summary>
        [Test]
        public void TimezoneAddressRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimezoneAddressRequest
            //Assert.IsInstanceOfType<TimezoneAddressRequest> (instance, "variable 'instance' is a TimezoneAddressRequest");
        }

        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Test]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }
        /// <summary>
        /// Test the property 'AddressTime'
        /// </summary>
        [Test]
        public void AddressTimeTest()
        {
            // TODO unit test for the property 'AddressTime'
        }

    }

}
