/* 
 * Location Intelligence APIs
 *
 * Incorporate our extensive geodata into everyday applications, business processes and workflows.
 *
 * OpenAPI spec version: 7.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pb.locationIntelligence.Api;
using pb.locationIntelligence.Model;
using pb.locationIntelligence.Client;
using System.Reflection;

namespace pb.locationIntelligence.Test
{
    /// <summary>
    ///  Class for testing UseTax
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UseTaxTests
    {
        // TODO uncomment below to declare an instance variable for UseTax
        //private UseTax instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UseTax
            //instance = new UseTax();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UseTax
        /// </summary>
        [Test]
        public void UseTaxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UseTax
            //Assert.IsInstanceOfType<UseTax> (instance, "variable 'instance' is a UseTax");
        }

        /// <summary>
        /// Test the property 'TotalTaxRate'
        /// </summary>
        [Test]
        public void TotalTaxRateTest()
        {
            // TODO unit test for the property 'TotalTaxRate'
        }
        /// <summary>
        /// Test the property 'TotalTaxAmount'
        /// </summary>
        [Test]
        public void TotalTaxAmountTest()
        {
            // TODO unit test for the property 'TotalTaxAmount'
        }
        /// <summary>
        /// Test the property 'StateTaxRate'
        /// </summary>
        [Test]
        public void StateTaxRateTest()
        {
            // TODO unit test for the property 'StateTaxRate'
        }
        /// <summary>
        /// Test the property 'StateTaxAmount'
        /// </summary>
        [Test]
        public void StateTaxAmountTest()
        {
            // TODO unit test for the property 'StateTaxAmount'
        }
        /// <summary>
        /// Test the property 'CountyTaxRate'
        /// </summary>
        [Test]
        public void CountyTaxRateTest()
        {
            // TODO unit test for the property 'CountyTaxRate'
        }
        /// <summary>
        /// Test the property 'CountyTaxAmount'
        /// </summary>
        [Test]
        public void CountyTaxAmountTest()
        {
            // TODO unit test for the property 'CountyTaxAmount'
        }
        /// <summary>
        /// Test the property 'MunicipalTaxRate'
        /// </summary>
        [Test]
        public void MunicipalTaxRateTest()
        {
            // TODO unit test for the property 'MunicipalTaxRate'
        }
        /// <summary>
        /// Test the property 'MunicipalTaxAmount'
        /// </summary>
        [Test]
        public void MunicipalTaxAmountTest()
        {
            // TODO unit test for the property 'MunicipalTaxAmount'
        }
        /// <summary>
        /// Test the property 'SpdsTax'
        /// </summary>
        [Test]
        public void SpdsTaxTest()
        {
            // TODO unit test for the property 'SpdsTax'
        }
        /// <summary>
        /// Test the property 'SpecialTaxRulesApplied'
        /// </summary>
        [Test]
        public void SpecialTaxRulesAppliedTest()
        {
            // TODO unit test for the property 'SpecialTaxRulesApplied'
        }
        /// <summary>
        /// Test the property 'SpecialTaxRulesDescriptor'
        /// </summary>
        [Test]
        public void SpecialTaxRulesDescriptorTest()
        {
            // TODO unit test for the property 'SpecialTaxRulesDescriptor'
        }

    }

}
